[build]
  command = "npm install && npm run build"
  publish = "dist/"

[template]
  incoming-hooks = ["Ghost"]

# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
    environment = { GHOST_API_URL = "super secret", GHOST_CONTENT_API_KEY = "abc", SITE_URL = "DEPLOY_URL" }